Id_Jogo = 0
League = 1
Season = 2
Date = 3
Rodada= 4
Home = 5
Away = 6
HT_Goals_H = 7
HT_Goals_A = 8
HT_TotalGoals = 9
FT_Goals_H = 10
FT_Goals_A = 11
FT_TotalGoals = 12
Goals_H_Minutes = 13
Goals_A_Minutes = 14
FT_Corners_H = 15
FT_Corners_A = 16
FT_TotalCorners = 17

HT_Odds_H               = 18
HT_Odds_D               = 19
HT_Odds_A               = 20
HT_Odds_Over05          = 21
HT_Odds_Under05         = 22
HT_Odds_Over15          = 23
HT_Odds_Under15         = 24
HT_Odds_Over25          = 25
HT_Odds_Under25         = 26
FT_Odds_H               = 27
FT_Odds_D               = 28
FT_Odds_A               = 29
FT_Odds_Over05          = 30
FT_Odds_Under05         = 31
FT_Odds_Over15          = 32
FT_Odds_Under15         = 33
FT_Odds_Over25          = 34
FT_Odds_Under25         = 35
Odds_BTTS_Yes           = 36
Odds_BTTS_No            = 37
Odds_DuplaChance_1X     = 38
Odds_DuplaChance_12     = 39
Odds_DuplaChance_X2     = 40
PPG_Home_Pre            = 41
PPG_Away_Pre            = 42
PPG_Home                = 43
PPG_Away                = 44
XG_Home_Pre             = 45
XG_Away_Pre             = 46
XG_Total_Pre            = 47
Odds_Corners_H          = 48
Odds_Corners_D          = 49
Odds_Corners_A          = 50
Odds_Corners_Over75     = 51
Odds_Corners_Over85     = 52
Odds_Corners_Over95     = 53
Odds_Corners_Over105    = 54
Odds_Corners_Over115    = 55
ShotsOnTarget_H         = 56
ShotsOnTarget_A         = 57
ShotsOffTarget_H        = 58
ShotsOffTarget_A        = 59
Shots_H                 = 60
Shots_A                 = 61


# PPG_Home_Pre = 18
# PPG_Away_Pre = 19
# PPG_Home = 20
# PPG_Away = 21
# XG_Home_Pre = 22
# XG_Away_Pre = 23
# XG_Total_Pre = 24
# ShotsOnTarget_H = 25
# ShotsOnTarget_A = 26
# ShotsOffTarget_H = 27
# ShotsOffTarget_A = 28
# Shots_H = 29
# Shots_A = 30

times = [
    "12 de Octubre",
    "1860 München",
    "AaB",
    "Aalesund",
    "Aarau",
    "ABC",
    "Aberdeen",
    "Aberystwyth Town",
    "Academico Viseu",
    "Accrington Stanley",
    "AC Milan",
    "AD Alcorcón",
    "Adana Demirspor",
    "Adelaide United",
    "Admira",
    "ADO Den Haag",
    "AEK Athens",
    "AEK Larnaca",
    "AFC Bournemouth",
    "AFC Eskilstuna",
    "AFC Wimbledon",
    "AGF",
    "AIK",
    "Airbus UK",
    "Ajaccio",
    "Ajax",
    "Ajax II",
    "Akhmat Grozny",
    "Al Ahly",
    "Alanyaspor",
    "Albacete Balompié",
    "Albion",
    "Albirex Niigata",
    "Aldosivi",
    "Alianza Lima",
    "Al Ittihad",
    "Al Masry",
    "Almere City",
    "Almería",
    "Al Mokawloon",
    "Altos",
    "Aluminij",
    "Amazonas",
    "América Mineiro",
    "América RN",
    "Amiens SC",
    "Amstetten",
    "Angers SCO",
    "Ankaragücü",
    "Annecy",
    "Ansan Greeners",
    "Antalyaspor",
    "Antofagasta",
    "Anyang",
    "Aparecidense",
    "Apollon",
    "Arda",
    "Argentinos Juniors",
    "Argeș",
    "Aris",
    "Arminia Bielefeld",
    "Arsenal",
    "Arsenal de Sarandí",
    "Åsane",
    "Asan Mugunghwa",
    "Ascoli",
    "AS Eupen",
    "Astana",
    "Asteras Tripolis",
    "Aston Villa",
    "Aswan FC",
    "Atalanta",
    "Athletic Club Bilbao",
    "Atlanta United FC",
    "Atlètic Club d'Escaldes",
    "Atlético GO",
    "Atlético Madrid",
    "Atlético Mineiro",
    "Atlético Nacional",
    "Atlético PR",
    "Atlético Tucumán",
    "Atromitos",
    "Audax Italiano",
    "Augsburg",
    "Austin",
    "Austria Klagenfurt",
    "Austria Lustenau",
    "Austria Wien",
    "Austria Wien II",
    "Auxerre",
    "Avaí",
    "Avispa Fukuoka",
    "AVS",
    "AZ",
    "AZ II",
    "Bačka Topola",
    "Baden",
    "Bahia",
    "Bala Town",
    "Ballkani",
    "Baltika",
    "Banants",
    "Banfield",
    "Baník Ostrava",
    "Barcelona",
    "Bari 1908",
    "Barnsley",
    "Barracas Central",
    "Barrow",
    "Barry Town United",
    "Basel",
    "Bastia",
    "BATE",
    "Bayer Leverkusen",
    "Bayern München",
    "Bayreuth",
    "Beerschot-Wilrijk",
    "Beijing Guoan",
    "Belenenses",
    "Belgrano",
    "Bellinzona",
    "Benevento",
    "Benfica",
    "Benfica II",
    "Beroe",
    "Beşiktaş",
    "Birmingham City",
    "Blackburn Rovers",
    "Blackpool",
    "Blaublitz Akita",
    "Blau-Weiß Linz",
    "Boavista FC",
    "Boca Juniors",
    "Bochum",
    "Bohemians",
    "Bohemians 1905",
    "Bolívar",
    "Bologna",
    "Bolton Wanderers",
    "Bordeaux",
    "Borussia Dortmund",
    "Borussia Dortmund II",
    "Borussia M'gladbach",
    "Boston River",
    "Botafogo",
    "Botafogo PB",
    "Botafogo SP",
    "Botev Plovdiv",
    "Botev Vratsa",
    "Botoşani",
    "Bradford City",
    "Bragantino",
    "Brage",
    "Brann",
    "Brasil de Pelotas",
    "Bravo",
    "Breidablik",
    "Brentford",
    "Brescia",
    "Brest",
    "Brighton & Hove Albion",
    "Brisbane Roar",
    "Bristol City",
    "Bristol Rovers",
    "Brommapojkarna",
    "Brøndby",
    "Brusque",
    "Bryne",
    "Bucheon 1995",
    "Budućnost",
    "Burgos CF",
    "Burnley",
    "Burton Albion",
    "Busan I'Park",
    "Cádiz",
    "Caen",
    "Caernarfon Town",
    "Cagliari",
    "Cambridge United",
    "Cambuur",
    "Campinense",
    "CA Osasuna",
    "Carabobo",
    "Caracas",
    "Cardiff City",
    "Cardiff MU",
    "Carlisle United",
    "Casa Pia",
    "Catanzaro",
    "CD Eldense",
    "CD El Nacional",
    "CD Feirense",
    "CD Lugo",
    "CD Mafra",
    "CD Nacional",
    "CD Tenerife",
    "CD Tondela",
    "CD Trofense",
    "CD Universidad Católica",
    "Ceará",
    "Celje",
    "Celta de Vigo",
    "Celtic",
    "Central Coast Mariners",
    "Central Córdoba SdE",
    "Ceramica Cleopatra",
    "Cercle Brugge",
    "Cerezo Osaka",
    "Cerrito",
    "Cerro",
    "Cerro Largo",
    "Cerro Porteño",
    "César Vallejo",
    "České Budějovice",
    "CF Os Belenenses",
    "CFR Cluj",
    "Changchun Yatai",
    "Chapecoense",
    "Charlotte",
    "Charlton Athletic",
    "Chelsea",
    "Cheltenham Town",
    "Chengdu Better City FC",
    "Cheonan City",
    "Cheongju",
    "Cherno More",
    "Chicago Fire",
    "Chindia Târgovişte",
    "Cittadella",
    "Clermont",
    "Club Always Ready",
    "Club Brugge",
    "Club Brugge II",
    "Cobresal",
    "Coca-Cola",
    "Colchester United",
    "Colo-Colo",
    "Colón",
    "Colorado Rapids",
    "Columbus Crew",
    "Colwyn Bay",
    "Como",
    "Concarneau",
    "Confiança",
    "Connah's Quay",
    "Consadole Sapporo",
    "Copiapó",
    "Coquimbo Unido",
    "Corinthians",
    "Coritiba",
    "Cork City",
    "Cosenza",
    "Coventry City",
    "Cracovia Kraków",
    "Crawley Town",
    "CRB",
    "Cremonese",
    "Crewe Alexandra",
    "Criciúma",
    "Cruzeiro",
    "Crystal Palace",
    "CSA",
    "CSD Independiente del Valle",
    "CS Emelec",
    "CSKA 1948 Sofia",
    "CSKA Moskva",
    "CSKA Sofia",
    "CS Marítimo",
    "CSM Iaşi",
    "CS U Craiova",
    "Cuiabá",
    "Čukarički",
    "Curicó Unido",
    "DAC",
    "Daegu",
    "Daejeon Citizen",
    "Dalian Yifang",
    "Dalkurd",
    "Danubio",
    "Darmstadt 98",
    "DC United",
    "Defensa y Justicia",
    "Defensor Sporting",
    "Degerfors",
    "De Graafschap",
    "Den Bosch",
    "Deportes Tolima",
    "Deportivo Alavés",
    "Deportivo Cali",
    "Deportivo Lara",
    "Deportivo Maldonado",
    "Deportivo Pereira",
    "Deportivo Táchira",
    "Derby County",
    "Derry City",
    "Dijon",
    "Dinamo Batumi",
    "Dinamo Bucureşti",
    "Dinamo Moskva",
    "Dinamo Tbilisi",
    "Dinamo Zagreb",
    "Djurgården",
    "Dnipro-1",
    "Domžale",
    "Doncaster Rovers",
    "Dordrecht",
    "Dornbirn",
    "Drogheda United",
    "Dukla Banská Bystrica",
    "Dundalk",
    "Dundee",
    "Dundee United",
    "Dunkerque",
    "Dynamo Dresden",
    "Dynamo Kyiv",
    "EC São José",
    "Eindhoven",
    "Eintracht Braunschweig",
    "Eintracht Frankfurt",
    "Elche CF",
    "El Daklyeh FC",
    "Elfsborg",
    "El Geish",
    "Elversberg",
    "Emmen",
    "Empoli",
    "ENPPI",
    "Erzgebirge Aue",
    "Estrela Amadora",
    "Estudiantes",
    "Etar",
    "Everton",
    "Excelsior",
    "Excelsior Virton",
    "Exeter City",
    "F91 Dudelange",
    "Fagiano Okayama",
    "Fakel",
    "Famalicão",
    "Farense",
    "Fatih Karagümrük",
    "FC Andorra",
    "FC Arouca",
    "FC Barcelona",
    "FC Cartagena",
    "FC Cincinnati",
    "FC Dallas",
    "FC Penafiel",
    "FCSB",
    "FC Schaffhausen",
    "FC Seoul",
    "FCV Dender EH",
    "FC Vizela",
    "Fenerbahçe",
    "Fénix",
    "FeralpiSalò",
    "Ferencváros",
    "Ferroviário",
    "Feyenoord",
    "FH",
    "Figueirense",
    "Finn Harps",
    "Fiorentina",
    "First Vienna",
    "FK Bodo - Glimt",
    "FK Košice",
    "FK Sochi",
    "Flamengo",
    "Fleetwood Town",
    "Flint Town United",
    "Floresta",
    "Floridsdorfer AC",
    "Fluminense",
    "Forest Green Rovers",
    "Fortaleza",
    "Fortuna Düsseldorf",
    "Fortuna Sittard",
    "Fram",
    "Francs Borains",
    "Fredrikstad",
    "Freiburg",
    "Freiburg II",
    "Frosinone",
    "Fujieda MYFC",
    "Fulham",
    "Fylkir",
    "GAIS",
    "Galatasaray",
    "Gamba Osaka",
    "Gangwon",
    "Gazişehir Gaziantep",
    "GD Chaves",
    "GD Estoril Praia",
    "Gefle",
    "General Caballero JLM",
    "Genoa",
    "Getafe CF",
    "Ghazl El Mehalla",
    "GIF Sundsvall",
    "Gillingham",
    "Gil Vicente",
    "Gimnasia La Plata",
    "Gimpo Citizen",
    "Giresunspor",
    "Girona FC",
    "Go Ahead Eagles",
    "Godoy Cruz",
    "Goiás",
    "Gorica",
    "Górnik Zabrze",
    "Granada CF",
    "Grasshopper",
    "Grazer AK",
    "Grêmio",
    "Grenoble Foot 38",
    "Greuther Fürth",
    "Grimsby Town",
    "Groningen",
    "Grorud",
    "Grulla Morioka",
    "Guaireña",
    "Guangzhou Evergrande",
    "Guangzhou R&F",
    "Guarani",
    "Guaraní",
    "Guingamp",
    "Gwangju",
    "Gyeongnam",
    "Häcken",
    "Hajduk Split",
    "Haka",
    "Hallescher FC",
    "Halmstad",
    "Hamburger SV",
    "HamKam",
    "Hammarby",
    "Hamrun Spartans",
    "Hannover 96",
    "Hansa Rostock",
    "Haras El Hodood",
    "Harju Jalgpallikool",
    "Harrogate Town",
    "Hartberg",
    "Hartlepool United",
    "Hatayspor",
    "Haugesund",
    "Haverfordwest County",
    "Hearts",
    "Hebar 1918",
    "Hebei CFFC",
    "Heerenveen",
    "Heidenheim",
    "Hellas Verona",
    "Helmond Sport",
    "Helsingborg",
    "Henan Jianye",
    "Heracles",
    "Hermannstadt",
    "Hertha BSC",
    "Hibernian",
    "Hibernians",
    "HIFK",
    "HJK",
    "HK",
    "Hødd",
    "Hoffenheim",
    "Holstein Kiel",
    "Honka",
    "Horn",
    "Horsens",
    "Houston Dynamo",
    "Hradec Králové",
    "Huachipato",
    "Huddersfield Town",
    "Hull City",
    "Huracán",
    "Hvidovre",
    "ÍA",
    "ÍBV",
    "IFK Göteborg",
    "Ilves",
    "IMT Novi Beograd",
    "Incheon United",
    "Independiente",
    "Independiente Medellín",
    "Independiente Petrolero",
    "Ingolstadt",
    "Instituto",
    "Inter Club d'Escaldes",
    "Inter Miami",
    "Inter Milan",
    "Internacional",
    "Inter Turku",
    "Ionikos",
    "Ipswich Town",
    "Ismaily SC",
    "İstanbul Başakşehir",
    "İstanbulspor",
    "Istra 1961",
    "Ituano",
    "Iwaki",
    "Jablonec",
    "Jagiellonia Białystok",
    "Jahn Regensburg",
    "Javor Ivanjica",
    "JEF United",
    "Jeju United",
    "Jeonbuk Motors",
    "Jeonnam Dragons",
    "Jerv",
    "Jönköpings Södra",
    "Jubilo Iwata",
    "Juventude",
    "Juventus",
    "KA",
    "KAA Gent",
    "Kaiserslautern",
    "Kalmar",
    "Kapfenberger SV",
    "Karlsruher SC",
    "Karviná",
    "Kashima Antlers",
    "Kashiwa Reysol",
    "Kasımpaşa",
    "Kawasaki Frontale",
    "Kayserispor",
    "Keflavík",
    "KFUM",
    "Khimki",
    "KÍ",
    "Kifisia",
    "Kilmarnock",
    "KMSK Deinze",
    "København",
    "Köln",
    "Kolubara",
    "Kongsvinger",
    "Konyaspor",
    "Koper",
    "Korona Kielce",
    "KR",
    "Krasnodar",
    "KRC Genk",
    "KRC Genk II",
    "Kristiansund",
    "Krylya Sovetov",
    "KTP",
    "KuPS",
    "Kuressaare",
    "KVC Westerlo",
    "KV Kortrijk",
    "KV Mechelen",
    "KV Oostende",
    "Kyoto Sanga",
    "La Fiorita",
    "Lafnitz",
    "LA Galaxy",
    "Lahti",
    "La Luz",
    "Lamia",
    "Landskrona",
    "Lanús",
    "Larne",
    "La Serena",
    "LASK Linz",
    "Lausanne Sport",
    "Laval",
    "Lazio",
    "Lecce",
    "Lecco",
    "Lechia Gdańsk",
    "Lech Poznań",
    "Leeds United",
    "Leganés",
    "Legia Warszawa",
    "Legion",
    "Le Havre",
    "Leicester City",
    "Leiknir Reykjavík",
    "Leixões",
    "Lens",
    "Leoben",
    "Levadiakos",
    "Levante UD",
    "Levski Krumovgrad",
    "Levski Sofia",
    "Leyton Orient",
    "Libertad",
    "Liefering",
    "Lierse Kempenzonen",
    "Lille",
    "Lillestrøm",
    "Lincoln City",
    "Lincoln Red Imps",
    "Linfield",
    "Liptovský Mikuláš",
    "Liverpool",
    "Liverpool FC Montevideo",
    "Livingston",
    "ŁKS Łódź",
    "Lokomotiva Zagreb",
    "Lokomotiv Moskva",
    "Lokomotiv Plovdiv",
    "Lokomotiv Sofia 1929",
    "Lommel United",
    "Londrina",
    "Lorient",
    "Los Angeles FC",
    "Ludogorets",
    "Lugano",
    "Luton Town",
    "Luzern",
    "Lyngby",
    "Macarthur",
    "Maccabi Haifa",
    "Machida Zelvia",
    "Magallanes",
    "Magdeburg",
    "Mainz 05",
    "Málaga CF",
    "Malmö FF",
    "Manaus",
    "Manchester City",
    "Manchester United",
    "Mansfield Town",
    "Maribor",
    "Mariehamn",
    "Meizhou Hakka",
    "Melbourne City FC",
    "Melbourne Victory FC",
    "Melgar",
    "Meppen",
    "Metropolitanos",
    "Metz",
    "Middlesbrough",
    "Midtjylland",
    "Miedź Legnica",
    "Millonarios",
    "Millwall",
    "Milton Keynes Dons",
    "Minnesota United",
    "Mioveni",
    "Mirandés",
    "Mirassol",
    "Mito Hollyhock",
    "Mjällby",
    "Mjøndalen",
    "Mladá Boleslav",
    "Mladost Lučani",
    "Mladost Novi Sad",
    "Modena",
    "Molde",
    "Monaco",
    "Monagas",
    "Montedio Yamagata",
    "Montpellier",
    "Montreal Impact",
    "Monza",
    "Morecambe",
    "Moreirense FC",
    "Moss",
    "Motherwell",
    "MSV Duisburg",
    "Mura",
    "MVV",
    "NAC Breda",
    "Nacional",
    "Nacional Asunción",
    "Nacional Potosí",
    "Nagoya Grampus",
    "Nantes",
    "Nantong Zhiyun",
    "Napoli",
    "Napredak",
    "Nashville SC",
    "National Bank of Egypt",
    "Náutico",
    "NEC",
    "Neuchâtel Xamax",
    "Newcastle Jets FC",
    "Newcastle United",
    "Newell's Old Boys",
    "New England Revolution",
    "Newport County",
    "Newtown",
    "New York City",
    "New York RB",
    "Nice",
    "Nîmes",
    "Niort",
    "Nõmme Kalju",
    "Nordsjælland",
    "Norrby",
    "Norrköping",
    "Northampton Town",
    "Norwich City",
    "Nottingham Forest",
    "Notts County",
    "Novi Pazar",
    "Novorizontino",
    "Ñublense",
    "Nürnberg",
    "OB",
    "Odd",
    "OFI",
    "OFK Pirin",
    "O'Higgins",
    "OH Leuven",
    "Oita Trinita",
    "Olimpia",
    "Olimpija",
    "Olimpiyets",
    "Olympiakos Piraeus",
    "Olympique Lyonnais",
    "Olympique Marseille",
    "Omiya Ardija",
    "Operário PR",
    "Örebro",
    "Orenburg",
    "Örgryte",
    "Orlando City",
    "Osijek",
    "Osnabrück",
    "Oss",
    "Öster",
    "Östersunds FK",
    "Oţelul Galaţi",
    "Oulu",
    "Oxford United",
    "Paços de Ferreira",
    "Paderborn",
    "Paide",
    "Palermo",
    "Palestino",
    "Palmeiras",
    "Panaitolikos",
    "Panathinaikos",
    "Panserraikos",
    "PAOK",
    "Pardubice",
    "Paris",
    "Parma",
    "Partizan",
    "Partizani Tirana",
    "PAS Giannina",
    "Patro Eisden",
    "Patronato",
    "Pau",
    "Paysandu",
    "PEC Zwolle",
    "Peñarol",
    "Pendikspor",
    "Penybont",
    "Perth Glory FC",
    "Perugia",
    "Peterborough United",
    "Petrolul 52",
    "Pharco",
    "Philadelphia Union",
    "Piast Gliwice",
    "Pisa",
    "Platense",
    "Plaza Colonia",
    "Plymouth Argyle",
    "Podbrezová",
    "Pogoń Szczecin",
    "Pohang Steelers",
    "Ponte Preta",
    "Pontypridd Town AFC",
    "Portimonense",
    "Portland Timbers",
    "Porto",
    "Porto II",
    "Portsmouth",
    "Port Vale",
    "Pouso Alegre",
    "Preston North End",
    "Preußen Münster",
    "PSG",
    "PSV",
    "PSV II",
    "Puszcza Niepołomice",
    "Pyramids FC",
    "Pyunik",
    "Qarabağ",
    "Qingdao Jonoon",
    "Queens Park Rangers",
    "Quevilly Rouen",
    "Racing",
    "Racing Club",
    "Racing Club de Ferrol",
    "Racing Santander",
    "Radnički Kragujevac",
    "Radnički Niš",
    "Radnik Surdulica",
    "Radomiak Radom",
    "Radomlje",
    "Raków Częstochowa",
    "Randers",
    "Rangers",
    "Ranheim",
    "Rapid Bucureşti",
    "Rapid Wien",
    "Rapid Wien II",
    "Raufoss",
    "Rayo Vallecano",
    "RB Leipzig",
    "RCD Espanyol",
    "RCD Mallorca",
    "Reading",
    "Real Betis",
    "Real Madrid",
    "Real Oviedo",
    "Real Salt Lake",
    "Real Sociedad",
    "Real Valladolid",
    "Real Zaragoza",
    "Red Star Belgrade",
    "Reggiana",
    "Reggina",
    "Reims",
    "Remo",
    "Rennes",
    "Renofa Yamaguchi",
    "Rentistas",
    "Resistencia",
    "RFC Liege",
    "RFC Seraing",
    "Rheindorf Altach",
    "Ried",
    "Rīgas FS",
    "Rijeka",
    "Rio Ave FC",
    "River Plate",
    "Rizespor",
    "RKC Waalwijk",
    "Roasso Kumamoto",
    "Rochdale",
    "Roda JC",
    "Rodez",
    "Rogaška",
    "Roma",
    "Rosario Central",
    "Rosenborg",
    "Ross County",
    "Rostov",
    "Rotherham United",
    "Rot-Weiss Essen",
    "Royal Antwerp FC",
    "RSC Anderlecht",
    "RSC Anderlecht II",
    "Rubin Kazan",
    "Ruch Chorzów",
    "Rudeš",
    "Ružomberok",
    "RWDM",
    "Ryūkyū",
    "Saarbrucken",
    "Sagan Tosu",
    "Saint-Étienne",
    "Salernitana",
    "Salford City",
    "Salzburg",
    "Sampaio Corrêa",
    "Sampdoria",
    "Samsunspor",
    "Sandefjord",
    "Sandhausen",
    "Sandnes Ulf",
    "Sanfrecce Hiroshima",
    "Sangju Sangmu",
    "San Lorenzo",
    "Santa Clara",
    "Santos",
    "São Bernardo",
    "São Paulo",
    "Sarmiento",
    "Sarpsborg 08",
    "Sassuolo",
    "Schalke 04",
    "Schwarz-Weiß Bregenz",
    "SD Amorebieta",
    "SD Aucas",
    "SD Eibar",
    "SD Huesca",
    "SD Ponferradina",
    "Seattle Sounders",
    "Seongnam",
    "Seoul E-Land",
    "Sepsi",
    "Septemvri Sofia",
    "Servette",
    "Sevilla FC",
    "Shakhtar Donetsk",
    "Shakhtyor",
    "Shamrock Rovers",
    "Shandong Luneng",
    "Shanghai Shenhua",
    "Shanghai SIPG",
    "Sheffield United",
    "Sheffield Wednesday",
    "Shelbourne",
    "Shenzhen",
    "Sheriff",
    "Shijiazhuang Ever Bright",
    "Shimizu S-Pulse",
    "Shkupi",
    "Shonan Bellmare",
    "Shrewsbury Town",
    "Šibenik",
    "Sigma Olomouc",
    "Silkeborg",
    "Sint-Truiden",
    "Sion",
    "Sirius",
    "Sivasspor",
    "SJ Earthquakes",
    "SJK",
    "Skalica",
    "Skeid",
    "Skövde AIK",
    "Śląsk Wrocław",
    "Slaven Koprivnica",
    "Slavia Praha",
    "Slavia Sofia",
    "Sligo Rovers",
    "Slovácko",
    "Slovan Bratislava",
    "Slovan Liberec",
    "Smouha SC",
    "Sochaux",
    "Sogndal",
    "Sol de América",
    "Southampton",
    "SPAL",
    "Spartak Moskva",
    "Spartak Subotica",
    "Spartak Trnava",
    "Spartak Varna",
    "Sparta Praha",
    "Sparta Rotterdam",
    "Spezia",
    "Sport Huancayo",
    "Sporting Braga",
    "Sporting Charleroi",
    "Sporting Covilhã",
    "Sporting CP",
    "Sporting Cristal",
    "Sporting Gijón",
    "Sporting KC",
    "Sportivo Ameliano",
    "Sportivo Luqueño",
    "Sportivo Trinidense",
    "Sport Recife",
    "SSC Farul",
    "Stabæk",
    "Stade Lausanne-Ouchy",
    "Stade Nyonnais",
    "Stal Mielec",
    "Standard Liège",
    "Standard Liège II",
    "Start",
    "Stevenage",
    "St. Gallen",
    "Stjarnan",
    "St. Johnstone",
    "Stjørdals-Blink",
    "St. Louis City",
    "St. Mirren",
    "Stockport County",
    "Stoke City",
    "St Patrick's Athl.",
    "St. Pauli",
    "St. Pölten",
    "Strasbourg",
    "Strømsgodset",
    "Struga",
    "Sturm Graz",
    "Sturm Graz II",
    "Stuttgart",
    "Südtirol",
    "Sunderland",
    "Sutjeska",
    "Sutton United",
    "Suwon",
    "Suwon Bluewings",
    "SV Stripfing Weiden",
    "Swansea City",
    "Swift Hesperange",
    "Swindon Town",
    "Sydney FC",
    "Tabor Sežana",
    "Tacuary",
    "Talleres Córdoba",
    "Tallinna FC Flora",
    "Tallinna FC Levadia",
    "Tallinna Kalev",
    "Tammeka",
    "Telstar",
    "Teplice",
    "Ternana",
    "The New Saints",
    "ThespaKusatsu Gunma",
    "The Strongest",
    "Thun",
    "Tianjin Teda",
    "Tigre",
    "Tirana",
    "Tobol",
    "Tochigi",
    "Tokushima Vortis",
    "Tokyo",
    "Tokyo Verdy",
    "Tombense",
    "Torino",
    "Toronto",
    "Torpedo Moskva",
    "Torque",
    "Torreense",
    "Tottenham Hotspur",
    "Toulouse",
    "Trabzonspor",
    "Tranmere Rovers",
    "Trans",
    "Trelleborg",
    "Trenčín",
    "Tre Penne",
    "Tromsø",
    "Troyes",
    "Twente",
    "UCD",
    "U Craiova 1948",
    "UD Ibiza",
    "Udinese",
    "UD Las Palmas",
    "UD Oliveirense",
    "Ulm",
    "Ulsan",
    "Ümraniyespor",
    "União de Leiria",
    "Uniclinic",
    "Union Berlin",
    "Unión Española",
    "Unión La Calera",
    "Union Saint-Gilloise",
    "Unión Santa Fe",
    "Universidad Católica",
    "Universidad Chile",
    "Universitario",
    "Universitatea Cluj",
    "Unterhaching",
    "Ural",
    "Urawa Reds",
    "UTA Arad",
    "Utrecht",
    "Utrecht II",
    "Utsikten",
    "Vaduz",
    "Valencia CF",
    "Valenciennes",
    "Vålerenga",
    "Valmiera / BSS",
    "Valur",
    "Vancouver Whitecaps",
    "Vaprus",
    "Varaždin",
    "Varberg",
    "Värnamo",
    "Vasco da Gama",
    "Västerås SK",
    "Vegalta Sendai",
    "Vejle",
    "Vélez Sarsfield",
    "Venezia",
    "Ventforet Kofu",
    "Verl",
    "VfB Lübeck",
    "VfB Oldenburg",
    "Viborg",
    "Viking",
    "Víkingur Reykjavík",
    "Viktoria Köln",
    "Viktoria Plzeň",
    "Vilafranquense",
    "Vila Nova",
    "Vilaverdense",
    "Villarreal",
    "Villarreal II",
    "Vissel Kobe",
    "Vitesse",
    "Vitória",
    "Vitória Guimarães",
    "Vojvodina",
    "Volendam",
    "Volos NFC",
    "Volta Redonda",
    "Voluntari",
    "Vorwärts Steyr",
    "Voždovac",
    "VPS",
    "V-Varen Nagasaki",
    "VVV",
    "Waasland-Beveren",
    "Waldhof Mannheim",
    "Walsall",
    "Wanderers",
    "Warta Poznań",
    "Watford",
    "Wattens",
    "Wehen Wiesbaden",
    "Wellington Phoenix",
    "Werder Bremen",
    "West Bromwich Albion",
    "Western Sydney Wanderers",
    "Western United",
    "West Ham United",
    "Widzew Łódź",
    "Wigan Athletic",
    "Wil",
    "Willem II",
    "Winterthur",
    "Wisła Płock",
    "Wolfsberger AC",
    "Wolfsburg",
    "Wolverhampton Wanderers",
    "Wrexham",
    "Wuhan Three Towns",
    "Wuhan Zall",
    "Wycombe Wanderers",
    "Yokohama",
    "Yokohama F. Marinos",
    "Young Boys",
    "Ypiranga Erechim",
    "Yverdon Sport",
    "Zagłębie Lubin",
    "Žalgiris",
    "Zamalek",
    "Zamora",
    "Zbrojovka Brno",
    "Železničar Pančevo",
    "Zemplín Michalovce",
    "Zenit",
    "Zhejiang FC",
    "Žilina",
    "Zlaté Moravce",
    "Zlín",
    "Zrinjski",
    "Zulte-Waregem",
    "Zürich",
    "Zweigen Kanazawa",
    "Zwickau",
]

temporadas = [
    "2022",
    "2022/2023",
    "2023",
    "2023/2024",
]

